# Generated by Django 3.0.2 on 2021-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210130_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.SlugField(max_length=15),
        ),
    ]
