# Generated by Django 3.0.2 on 2021-01-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210130_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserRole'),
        ),
    ]
