# Generated by Django 3.1.4 on 2021-01-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('promo', models.BooleanField(default=True)),
                ('qry_jobs', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date_payroll', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hairstore.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hairstore.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hairstore.job')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hairstore.hiretype'),
        ),
    ]
